# Generated by Django 3.2 on 2021-04-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_bookapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookApp',
        ),
    ]
